const TEXAS_COMPLIANCE_REQUIREMENTS = [
  {
    id: 'req-001',
    name: 'Orientation Training',
    description: 'Emergency procedures, abuse reporting, policies',
    category: 'Staff Training',
    priority: 'Medium-High',
    dueDate: 'Within 7 days of hire',
    frequency: 'one-time',
    texasCode: '§744.1301',
  },
  {
    id: 'req-002',
    name: 'Pre-Service Training',
    description: '8 clock hours on child development & safety',
    category: 'Staff Training',
    priority: 'Medium-High',
    dueDate: 'Within 90 days of hire',
    frequency: 'one-time',
    texasCode: '§744.1305',
  },
  {
    id: 'req-003',
    name: 'Annual Training Hours',
    description: '15 hours for staff, 20 for directors',
    category: 'Staff Training',
    priority: 'High',
    dueDate: 'Annually',
    frequency: 'annual',
    texasCode: '§744.1309',
  },
  {
    id: 'req-004',
    name: 'Background Checks',
    description: 'FBI fingerprint clearance for all staff',
    category: 'Staff Vetting',
    priority: 'High',
    dueDate: 'Before hire',
    frequency: 'every-5-years',
    texasCode: '§744.1081',
  },
  {
    id: 'req-005',
    name: 'TB Screening',
    description: 'Tuberculosis screening required',
    category: 'Health',
    priority: 'Medium-High',
    dueDate: 'Before hire',
    frequency: 'one-time',
    texasCode: '§744.1203',
  },
  {
    id: 'req-006',
    name: 'Incident Reporting',
    description: 'Report serious incidents to DFPS within 24 hours',
    category: 'Documentation',
    priority: 'High',
    dueDate: 'Within 24 hours',
    frequency: 'as-needed',
    texasCode: '§744.2203',
  },
  {
    id: 'req-007',
    name: 'Fire/Emergency Drills',
    description: 'Monthly fire drills required',
    category: 'Safety',
    priority: 'High',
    dueDate: 'Monthly',
    frequency: 'monthly',
    texasCode: '§744.2301',
  },
  {
    id: 'req-008',
    name: 'License Posting',
    description: 'Current license must be posted prominently',
    category: 'Licensing',
    priority: 'High',
    dueDate: 'Always',
    frequency: 'ongoing',
    texasCode: '§744.205',
  },
  {
    id: 'req-009',
    name: 'Medication Authorization',
    description: 'Signed parental authorization required',
    category: 'Medication',
    priority: 'High',
    dueDate: 'Before administration',
    frequency: 'as-needed',
    texasCode: '§744.2653',
  },
  {
    id: 'req-010',
    name: 'Child Immunization Records',
    description: 'Current immunization records on file',
    category: 'Health',
    priority: 'Medium-High',
    dueDate: 'Within 10 days of enrollment',
    frequency: 'ongoing',
    texasCode: '§744.801',
  },
  {
    id: 'req-011',
    name: 'CPR/First Aid Certification',
    description: 'At least one staff member per group certified',
    category: 'Safety',
    priority: 'High',
    dueDate: 'Always',
    frequency: 'every-2-years',
    texasCode: '§744.1115',
  },
  {
    id: 'req-012',
    name: 'Daily Attendance Records',
    description: 'Accurate daily attendance tracking',
    category: 'Documentation',
    priority: 'Medium',
    dueDate: 'Daily',
    frequency: 'daily',
    texasCode: '§744.1301',
  },
];

const STAFF_ROLES = [
  'Director',
  'Lead Teacher',
  'Assistant Teacher',
  'Floater',
  'Cook',
  'Administrative Staff'
];

const INCIDENT_TYPES = [
  'injury',
  'illness',
  'behavior'
];

module.exports = {
  TEXAS_COMPLIANCE_REQUIREMENTS,
  STAFF_ROLES,
  INCIDENT_TYPES
};
